### ISSUE TITLE
Support for ArrayBuffers

### ISSUE THREAD

**Issue by jq-rs** [HomeControlAS/cordova-plugin-advanced-websocket#15]
Currently Advanced WebSocket plugin supports only String format of messages. Support for ArrayBuffer-type would complete the plugin for generic use.

This is a standard feature of common browsers and set with command:
	webSocket.binaryType = "arraybuffer";

Thanks!

**Comment by chax** [comment]
You are right, this websocket client works only with strings. I'm not sure i have time to fix this very soon but feel free to submit PR with your solution, i will gladly review it and if it's good merge it.

**Comment by jq-rs** [comment]
Thanks! It seems I don't need it at the moment, so closing this one.
