### ISSUE TITLE
Software caused connection abort

### ISSUE THREAD

**Issue by EinfachHans** [HomeControlAS/cordova-plugin-advanced-websocket#20]
We currently have some Error Reports that Websockets are not working correctly. After investigating into this and sending device logs to server. We have very muchof these errors:

```{"webSocketId":"f7653acf-f03e-4f04-8523-9277556df169","code":1006,"exception":"Read error: ssl=0x71d93c2208: I/O error during system call, Software caused connection abort","callbackMethod":"onFail"}```

If this happens, our apps try to reconnect and this happens again, after sending / receiving 1-2 messages.

Can you please investigate into this and help me out? 😊

**Comment by EinfachHans** [comment]
@chax Anything you ca do here? We have a highly important app (works with the police / emergency data / live position updates) - this is quite important for us!

**Comment by chax** [comment]
This to me looks like a Server error, but I can't be sure without some more details. Did you try with pure http websockets api?

**Comment by EinfachHans** [comment]
@chax - i don't think so, we have no error there and this problem is new after rewriting the app hybrid with cordova (it was native before). Because the app is a german emergency app, it needs to have the websockets open over hours if the app runs minimized in background. That does not work with http websockets 😕

**Comment by EinfachHans** [comment]
Closed as we switched to Push Notifications
