### ISSUE TITLE
Can we use it directly as mqtt client?

### ISSUE THREAD

**Issue by yashkatta** [HomeControlAS/cordova-plugin-advanced-websocket#7]

**Comment by chax** [comment]
Please elaborate.

**Comment by chax** [comment]
WebSocket and MQTT are two completely different protocols and one doesn't have anything to do with the other.

Please read following links:
https://en.wikipedia.org/wiki/WebSocket
https://en.wikipedia.org/wiki/MQTT

**Comment by yashkatta** [comment]
Okey.
